<?php
return array (
  'license' => 
  array (
    'fieldid' => '173',
    'modelid' => '13',
    'siteid' => '0',
    'field' => 'license',
    'name' => '营业执照',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '15',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'orgcode' => 
  array (
    'fieldid' => '174',
    'modelid' => '13',
    'siteid' => '0',
    'field' => 'orgcode',
    'name' => '组织机构代码',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '15',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>