<?php
return array (
  'title' => '家电分类导航',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '常用家电',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3366,3367,3368,3369,3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '卫浴家电',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3372,3373,3374,3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '厨房家电',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '家庭影音',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3364,3387,3388,3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '小家电',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3365,3390,3391,3392,3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '液晶电视',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3366',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '等离子电视',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3367',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '空调',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3368',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '冰箱',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3369',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '洗衣机',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '电热水器',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '太阳能热水器',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '浴霸',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '燃气热水器',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '抽油烟机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '电饭煲',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '豆浆机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '榨汁机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '电饼铛电磁炉',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '微波炉',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '咖啡机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '消毒柜',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '饮水机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '多士炉',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '洗碗机',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '家庭影院',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => 'DVD播放机',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '迷你组合音响',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '电暖气',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '电风扇',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '电熨斗',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '收音机',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>