<?php
return array (
  41 => 
  array (
    'catid' => '41',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '41,42',
    'catname' => '行业资讯',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'hyzx',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=content&c=index&a=lists&catid=41',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'cban\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_hyzx\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xingyezixun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  44 => 
  array (
    'catid' => '44',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '17',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '44',
    'catname' => '展会信息',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'zhxx',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=content&c=index&a=lists&catid=44',
    'items' => '3',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'1\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'cban\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_zhxx\',
  \'show_template\' => \'show_zhxx\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhanhuixinxi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '1',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '2',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => '千县万店',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=cban&c=index&a=qxwd',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => '',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => NULL,
    'content_ishtml' => NULL,
    'category_ruleid' => NULL,
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '2',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => '家电名企',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=cban&c=index&a=jdmq',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '6',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => '',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => NULL,
    'content_ishtml' => NULL,
    'category_ruleid' => NULL,
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  46 => 
  array (
    'catid' => '46',
    'siteid' => '1',
    'type' => '2',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => '商机资讯',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=cban&c=index&a=supply',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => '',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => NULL,
    'content_ishtml' => NULL,
    'category_ruleid' => NULL,
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '门店信息发布',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'mdxxfb',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '1',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'1\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'cban\',
  \'category_template\' => \'category\',
  \'list_template\' => \'\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '19',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'mendianxinxifabu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '1',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '16',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '企业信息发布',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'qyxxfb',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '2',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'1\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'cban\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '20',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'qiyexinxifabu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '1',
    'isdomain' => '0',
  ),
  42 => 
  array (
    'catid' => '42',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '41',
    'arrparentid' => '0,41',
    'child' => '0',
    'arrchildid' => '42',
    'catname' => '家电新闻',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'hyzx/',
    'catdir' => 'jdxw',
    'url' => 'http://127.0.0.1:8080/cban/index.php?m=content&c=index&a=lists&catid=42',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'cban\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_hyzx\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '42',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jiadianxinwen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>