<?php
return array (
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页头条推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '15',
    'catid' => '0',
    'name' => '家电维修_维修网点图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '8',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '15',
    'catid' => '0',
    'name' => '家电维修_新加维修网点',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '7',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '15',
    'catid' => '9',
    'name' => '千县万店_门店图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '6',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '15',
    'catid' => '9',
    'name' => '千县万店_新加门店',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '5',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '17',
    'catid' => '44',
    'name' => '展会信息_展会图片资讯',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '17',
    'catid' => '44',
    'name' => '展会信息_热点展会排行',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '3',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '16',
    'catid' => '10',
    'name' => '家电名企_最新入驻家电企业',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '16',
    'catid' => '10',
    'name' => '家电名企_本月热门家电厂商',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>