<?php
return array (
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置1_图片新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置5',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  6 => 
  array (
    'posid' => '6',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置6',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  7 => 
  array (
    'posid' => '7',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置7',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置8',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置9',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置10',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  11 => 
  array (
    'posid' => '11',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置11',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置12',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置13',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置14',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置15',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置16',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  49 => 
  array (
    'posid' => '49',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置17',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  4 => 
  array (
    'posid' => '4',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置4_展会信息',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  3 => 
  array (
    'posid' => '3',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置3',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_位置2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品首页_家电排行_热水器',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '18',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品首页_家电排行_空调',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '17',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品首页_家电排行_洗衣机',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '16',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品首页_家电排行_冰箱',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '15',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品首页_家电排行_电视',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '14',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品文章页_最新单品资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '13',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '18',
    'catid' => '49',
    'name' => '畅销单品文章页_热销单品排行',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '12',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '1',
    'catid' => '41',
    'name' => '行业资讯_推荐图片新闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '11',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '1',
    'catid' => '41',
    'name' => '行业资讯_综合排行',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '1',
    'catid' => '41',
    'name' => '行业资讯_新闻点击排行',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '9',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '15',
    'catid' => '0',
    'name' => '家电维修_维修网点图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '8',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '15',
    'catid' => '0',
    'name' => '家电维修_新加维修网点',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '7',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '15',
    'catid' => '9',
    'name' => '千县万店_门店图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '6',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '15',
    'catid' => '9',
    'name' => '千县万店_新加门店',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '5',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '17',
    'catid' => '44',
    'name' => '展会信息_展会图片资讯',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '17',
    'catid' => '44',
    'name' => '展会信息_热点展会排行',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '3',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '16',
    'catid' => '10',
    'name' => '家电名企_最新入驻家电企业',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '16',
    'catid' => '10',
    'name' => '家电名企_本月热门家电厂商',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>